# Pin npm packages by running ./bin/importmap

pin "application", preload: true
pin "@hotwired/turbo", to: "https://ga.jspm.io/npm:@hotwired/turbo@7.1.0/dist/turbo.es2017-esm.js"
pin "@rails/actioncable/src", to: "https://ga.jspm.io/npm:@rails/actioncable@7.0.2/src/index.js"
pin "bootstrap", to: "https://ga.jspm.io/npm:bootstrap@5.1.3/dist/js/bootstrap.esm.js"
pin "@popperjs/core", to: "https://ga.jspm.io/npm:@popperjs/core@2.11.2/lib/index.js"
pin "jquery", to: "https://ga.jspm.io/npm:jquery@3.6.0/dist/jquery.js", preload: true
pin "select2", to: "https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"
pin "@nathanvda/cocoon", to: "https://ga.jspm.io/npm:@nathanvda/cocoon@1.2.14/cocoon.js"
pin "@hotwired/stimulus", to: "stimulus.min.js", preload: true
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js", preload: true
pin_all_from "app/javascript/controllers", under: "controllers"
pin_all_from 'app/javascript/components', under: 'components'
pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true
pin "js-cookie", to: "https://ga.jspm.io/npm:js-cookie@3.0.1/dist/js.cookie.mjs"
pin "lodash", to: "https://ga.jspm.io/npm:lodash@4.17.21/lodash.js"
pin "d3-dtree", to: "https://ga.jspm.io/npm:d3-dtree@2.4.1/dist/dTree.js"
pin "d3", to: "https://ga.jspm.io/npm:d3@4.13.0/build/d3.node.js"
pin "buffer", to: "https://ga.jspm.io/npm:@jspm/core@2.1.0/nodelibs/browser/buffer.js"
pin "child_process", to: "https://ga.jspm.io/npm:@jspm/core@2.1.0/nodelibs/browser/child_process.js"
pin "d3-array", to: "https://ga.jspm.io/npm:d3-array@1.2.1/build/d3-array.js"
pin "d3-axis", to: "https://ga.jspm.io/npm:d3-axis@1.0.8/build/d3-axis.js"
pin "d3-brush", to: "https://ga.jspm.io/npm:d3-brush@1.0.4/build/d3-brush.js"
pin "d3-chord", to: "https://ga.jspm.io/npm:d3-chord@1.0.4/build/d3-chord.js"
pin "d3-collection", to: "https://ga.jspm.io/npm:d3-collection@1.0.4/build/d3-collection.js"
pin "d3-color", to: "https://ga.jspm.io/npm:d3-color@1.0.3/build/d3-color.js"
pin "d3-dispatch", to: "https://ga.jspm.io/npm:d3-dispatch@1.0.3/build/d3-dispatch.js"
pin "d3-drag", to: "https://ga.jspm.io/npm:d3-drag@1.2.1/build/d3-drag.js"
pin "d3-dsv", to: "https://ga.jspm.io/npm:d3-dsv@1.0.8/build/d3-dsv.js"
pin "d3-ease", to: "https://ga.jspm.io/npm:d3-ease@1.0.3/build/d3-ease.js"
pin "d3-force", to: "https://ga.jspm.io/npm:d3-force@1.1.0/build/d3-force.js"
pin "d3-format", to: "https://ga.jspm.io/npm:d3-format@1.2.2/build/d3-format.js"
pin "d3-geo", to: "https://ga.jspm.io/npm:d3-geo@1.9.1/build/d3-geo.js"
pin "d3-hierarchy", to: "https://ga.jspm.io/npm:d3-hierarchy@1.1.5/build/d3-hierarchy.js"
pin "d3-interpolate", to: "https://ga.jspm.io/npm:d3-interpolate@1.1.6/build/d3-interpolate.js"
pin "d3-path", to: "https://ga.jspm.io/npm:d3-path@1.0.5/build/d3-path.js"
pin "d3-polygon", to: "https://ga.jspm.io/npm:d3-polygon@1.0.3/build/d3-polygon.js"
pin "d3-quadtree", to: "https://ga.jspm.io/npm:d3-quadtree@1.0.3/build/d3-quadtree.js"
pin "d3-queue", to: "https://ga.jspm.io/npm:d3-queue@3.0.7/build/d3-queue.js"
pin "d3-random", to: "https://ga.jspm.io/npm:d3-random@1.1.0/build/d3-random.js"
pin "d3-request", to: "https://ga.jspm.io/npm:d3-request@1.0.6/build/d3-request.node.js"
pin "d3-scale", to: "https://ga.jspm.io/npm:d3-scale@1.0.7/build/d3-scale.js"
pin "d3-selection", to: "https://ga.jspm.io/npm:d3-selection@1.3.0/dist/d3-selection.js"
pin "d3-shape", to: "https://ga.jspm.io/npm:d3-shape@1.2.0/build/d3-shape.js"
pin "d3-time", to: "https://ga.jspm.io/npm:d3-time@1.0.8/build/d3-time.js"
pin "d3-time-format", to: "https://ga.jspm.io/npm:d3-time-format@2.1.1/build/d3-time-format.js"
pin "d3-timer", to: "https://ga.jspm.io/npm:d3-timer@1.0.7/build/d3-timer.js"
pin "d3-transition", to: "https://ga.jspm.io/npm:d3-transition@1.1.1/build/d3-transition.js"
pin "d3-voronoi", to: "https://ga.jspm.io/npm:d3-voronoi@1.1.2/build/d3-voronoi.js"
pin "d3-zoom", to: "https://ga.jspm.io/npm:d3-zoom@1.7.1/build/d3-zoom.js"
pin "fs", to: "https://ga.jspm.io/npm:@jspm/core@2.1.0/nodelibs/browser/fs.js"
pin "http", to: "https://ga.jspm.io/npm:@jspm/core@2.1.0/nodelibs/browser/http.js"
pin "https", to: "https://ga.jspm.io/npm:@jspm/core@2.1.0/nodelibs/browser/https.js"
pin "process", to: "https://ga.jspm.io/npm:@jspm/core@2.1.0/nodelibs/browser/process-production.js"
pin "url", to: "https://ga.jspm.io/npm:@jspm/core@2.1.0/nodelibs/browser/url.js"
pin "xmlhttprequest", to: "https://ga.jspm.io/npm:xmlhttprequest@1.8.0/lib/XMLHttpRequest.js"
