name: Release

# Controls when the workflow will run
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run containers
        run: >
          ROUTER_NAME=tiedeapp_prod
          DOMAIN=tiede.app
          IMAGE_TAG=prod
          RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          GITHUB_REF=${{ github.ref }}
          POSTGRES_HOSTNAME=XbFkVz
          /usr/local/bin/docker-compose --file docker-compose.yml --project-name tiedeapp_prod up --detach --remove-orphans --build
